<?php

namespace App\Models\Traits;

use Illuminate\Support\Str;

/**
 *
 */
trait UuidTrait
{
    /**
     * @return void
     */
    protected static function booted(): void
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->id = Str::uuid()->toString();
        });
    }

}
